apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: goal-tracker
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: goalsdb
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_NAME: goalsdb
